export const GETTING_SERVICELOCATORS = 'GETTING_SERVICELOCATORS';
export const ERROR_GETTING_SERVICELOCATORS = 'ERROR_GETTING_SERVICELOCATORS';
export const REFRSHING_SERVICELOCATORS = 'REFRSHING_SERVICELOCATORS';
export const ERROR_REFRSHING_SERVICELOCATORS = 'ERROR_REFRSHING_SERVICELOCATORS';
